### ISSUE TITLE
ndx-events 0.3.0 or 0.2.0?

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/schneider-lab-to-nwb#11]
Should which version of ndx-events should this conversion use?

**Comment by pauladkisson** [comment]
I was under the impression that 0.3.0 was coming out soon, so I started using it for this conversion. Is that not the case @rly?

**Comment by h-mayorquin** [comment]
Reading the discussion here it seems that there is some disagreement in the TAB about the current schema:

https://docs.google.com/document/d/1qcsjyFVX9oI_746RdMoDdmQPu940s0YtDjb1en1Xtdw/edit?usp=sharing

The document also mentions that some backward compatibility effort would have to be carried out once the ndx-events is integrated into the main schema/pynwb. Basically, some code to coerce the old data types (.e.g ndx-events 2.0) into whatever we end up accepting into pynwb. This is good because visualizations/analysis will end up working with previous datasets that are already in dandi (those that used the data types of ndx-events 2.0 for example). 

The problem with releasing ndx-events in its current state is that it would increase the amount of backward compatibility effort that would be needed when the integration finally happens. If the code changes before the release this might mean that future visualizations and analysis will not work for the nwb files constructed with unreleased data types. 

I discussed this with @weiglszonja in the morning. I think this is a good point to bring and discuss to the LNWB - CN dev synch meeting.

**Comment by rly** [comment]
@h-mayorquin is correct. We are targeting a final resolution of ndx-events by the end of the month. We have a TAB meeting on Nov. 4. We could either release 0.3.0 now and have to adapt this schema (as well as 0.2.0) to the final version after merging into core, or we could wait. On your end, I would recommend using 0.3.0 only if we release it. Otherwise, use 0.2.0 or wait. Let me know your thoughts. I don't want to hold back progress, but at the same time, I am a bit concerned about having another version of the extension to maintain backwards compatibility with.

**Comment by pauladkisson** [comment]
Ok, thanks for the clarification. 

With all that in mind I think I will leave things as they are in this conversion right now. Then, if 0.3.0 still isn't released before the final meeting I will change things over to 0.2.0.
